print('Введите кличку животного:')
name = input()
print('Введите возраст животного:')
age = input()
print('Это желторотый питон по кличке "{name}". Возраст: {age} года(лет).'.format(name = name, age = age))